### ISSUE TITLE
layout distortion in oauth introduction

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/Auth-API#28]
![Screenshot from 2020-05-13 03-01-10](https://user-images.githubusercontent.com/13948542/81747663-1da4da80-94c6-11ea-9b26-dc2c2d1f2dee.png)

---

Layout of providers requires change!

**Comment by jaykay12** [comment]
**Requirements**

```yaml
{
  "developer": "Jalaz Kumar",
  "info": "Basic oAuth API",
  "providers": {
    "facebook": "<api.oauth.FacebookSignIn object at 0x7f13f4124f60>",
    "twitter": "<api.oauth.TwitterSignIn object at 0x7f13f41242e8>",
    "github": "<api.oauth.GithubSignIn object at 0x7f13f41362e8>",
    "google": "<api.oauth.GoogleSignIn object at 0x7f13f4136438>",
    "linkedin": "<api.oauth.LinkedInSignIn object at 0x7f13f4136470>"
  }
}
```

---

![Screenshot from 2020-05-14 16-29-40](https://user-images.githubusercontent.com/13948542/81926834-3b765a80-9600-11ea-9f61-0cff664533c5.png)
![Screenshot from 2020-05-14 16-29-54](https://user-images.githubusercontent.com/13948542/81926835-3ca78780-9600-11ea-9614-e30442d0cb73.png)
